apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: user-andre
  description: Local user for RHDH
spec:
  type: url
  target: https://raw.githubusercontent.com/andrevtg/backstage-dummy-users/refs/heads/main/catalog/user-andre.yaml
  rules:
    - allow:
        - User

---

apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: group-admin
  description: Local admin group for RHDH
spec:
  type: url
  target: https://raw.githubusercontent.com/andrevtg/backstage-dummy-users/refs/heads/main/catalog/group-admin.yaml
  rules:
    - allow:
        - Group
